services:
  db:
    container_name: my_portfolio_db
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./srcs
    ports:
      - "80:3000"
    environment:
      JWT_SECRET: testsecretkey-mchina-fiha
      DATABASE_URL: "postgresql://myuser:mypassword@my_portfolio_db:5432/mydb?schema=public"
    volumes:
      - ./srcs:/app
      - /app/node_modules  # Prevent host node_modules override
    depends_on:
      - db

volumes:
  postgres_data: